#!/usr/bin/env bash
# script that displays DNS info for a domain and subdomain

get_dns_info() {
	local subdomain="$1"
	local domain="$1"
	local record_type="$3"
	local destination="$4"

	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

main() {
	local domain="$1"
	local subdomain="$2"

	subdomains=("www" "lb-01" "web-01" "web-02")

	if [ -n "$subdomain" ]; then
		subdomains=("$subdomain")
	fi

	for subdomain in "${subdomains[@]}"; do
		result=$(dig "$subdomain.$domain" +short)

		if [ -n "$result" ]; then
			record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk '/IN/ {print $4}')
			get_dns_info "$subdomain" "$domain" "$record_type" "$result"
		fi
	done
}

if [ "$#" -lt 1 ]; then
	echo "Usage: $0 <domain> [subdomain]"
	exit 1
fi

main "$@"
