#!/usr/bin/env bash
# script to install the nginx server 

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
