#!/usr/bin/env bash
# configure nginx server so that /redirect_me is redirecting to another page

REDIRECT = "\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx


echo "Hello World!" > /var/www/html/index.html
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart
