#!/usr/bin/env bash
# configure nginx server to have a custom 404 page that contains
# Ceci n'est pas une page

REDIRECT_301 ="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
NOTFOUND_404 ="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
PATTERN ="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx


echo "Hello World!" > /var/www/html/index.html
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "s@$PATTERN@$NOTFOUND_404@" /etc/nginx/sites-available/default
sudo service nginx restart
