#!/usr/bin/env bash
# configure Nginx so that it's HTTP response contains a custom header

# update package manager
sudo apt-get -y update

# install nginx
sudo apt-get -y install nginx

# define custom nginx directives
custom_header="add_header X-Served-By \$HOSTNAME;"
add_404="error_page 404 /custom_404.html;"
redirect="rewrite ^/redirect_me https://www.youtube.com permanent;"

# default html page
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

# add custom header 
sudo sed -i "/listen 80 default_server;/a $custom_header" /etc/nginx/sites-available/default

# add redirect 
sudo sed -i "/listen 80 default_server;/a $redirect" /etc/nginx/sites-available/default

# custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# custom 404 directive
sudo sed -i "/listen 80 default_server;/a $add_404" /etc/nginx/sites-available/default

# restart nginx to apply changes
sudo service nginx restart
