#!/usr/bin/env bash
# Install and configure HAproxy on the lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

frontend="frontend http-in"
frontend+="\n\tbind *:80"
frontend+="\n\tdefault_backend servers"

backend="backend servers"
backend+="\n\tbalance roundrobin"
backend+="\n\tserver 343765-web-01 100.25.153.47:80 check"
backend+="\n\tserver 343765-web-02 52.87.22.215:80 check"

haproxy_config="/etc/haproxy/haproxy.cfg"

echo -e "$frontend" | sudo tee -a "$haproxy_config" > /dev/null
echo -e "$backend" | sudo tee -a "$haproxy_config" > /dev/null

sudo service haproxy restart
