#!/usr/bin/env bash
# install and configure HAproxy in the lb-01 server

sudo apt-get -y update

# install haproxy
sudo apt-get -y install haproxy

# create a temporary HAproxy configuration file
sudo tee /etc/haproxy/haproxy.cfg.tmp > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 343765-web-01 100.25.153.47:80 check
    server 343765-web-02 52.87.22.215:80 check
EOF

# replace original config with temporary config
sudo mv /etc/haproxy/haproxy.cfg.tmp /etc/haproxy/haproxy.cfg

# restart haproxy service
sudo service haproxy restart
