#!/usr/bin/env bash
# display a list of the current running processes
# display processes for all users, including those which might not have TTY
# display in a user-oriented format
# show process hierarchy

ps -auxf
