#!/usr/bin/env bash
# genarates numbers from 1 to 100
# displays "FizzBuzz" when number is a multiple of three and 5
# displays "Fizz" when number is multiple of 3
# displays "Buzz" whne the number is a multiple of 5
# otherwise displays the number in a list format

for i in {1..100}
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
