#!/usr/bin/env bash
# this script displays "Hi" at the 9th iteration

i=0
while (( i < 10 ))
do
	echo "Best School"
	if (( i == 8 ))
	then
		echo "Hi"
	fi
	(( i++ ))
done

# alt
# i=0
# while [ $i -lt 10 ]
# do
#	echo "Best School"
#	if [ $i -eq 9 ]
#	then
#		echo "Hi"
#	fi
#	(( i++ ))
# done
