#!/usr/bin/env bash
# displays the content of the current directory
# in a list format
# where only the part of the name after the first dash `-` is displayed

current=$(ls)
for i in $current
do
	echo "$i" | cut -d '-' -f2
done
