#!/usr/bin/env bash
# fix web server to run nginx as nginx user
# nginx must be listening on all actice IPs on port 8080

echo "user nginx;" >> /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
