#!/usr/bin/env bash
# redo of task 1
echo "user nginx;" >> /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx start
